### ISSUE TITLE
Use element content as msgid

### ISSUE THREAD

**Issue by pkaske** [ebidel/i18n-msg#12]
What are your thoughts on this? Wouldn't it be more convenient to use the inner content of the element and get rid of the msgid attribute / make the msgid optional.

**Comment by ebidel** [comment]
Currently, you can use textContent as a fallback case. If the language file doesn't exist or if the element is not upgraded. Removing `msgid` also means we wouldn't be able to lookup the message programmatically (without touching the DOM, etc).
