### ISSUE TITLE
not loading translation when using in dom-repeat (giving msgid value by data-binding)

### ISSUE THREAD

**Issue by carolirod** [ebidel/i18n-msg#15]
When using i18n-msg in a dom-repeat (giving msgid value by data-binding), it seems that the i18n-msg can't load the translations.

Maybe this could be happening because i18n-msg doesn't find the i18n-elements which are created in the dom-repeat.

thanks

**Comment by carolirod** [comment]
Not really a problem actually (sorry!), solved by defining+listening to document.documentElement.lang previously

this.value = document.documentElement.lang;
I18nMsg.lang = this.value;

**Comment by zukkun** [comment]
@carolirod It is not truly solved. The problem occur when Element reattach.
i18n-msg contain a bug.

`getMsg` is return `lang[msgId].message`. Although reference to `getMsg(this.msgid).message`.

```javascript
    attached: function() {
      var msg = this.getMsg(this.msgid)
      if (msg && msg.message) {
        this.innerHTML = msg.message;
      }
    },
```

```javascript
    getMsg: function(opt_msgId) {
      var msgId = opt_msgId || this.msgid;
      var lang = this.locales[this.language];
      if (lang && lang[msgId]) {
        return lang[msgId].message;
      }
      return null;
    },
```

Can you reopen this issue?

**Comment by carolirod** [comment]
mm ok I think you understand better the issue, I guess I have workaround working then.
I reopen then

**Comment by zukkun** [comment]
@ebidel Would it be possible to fix?

**Comment by ebidel** [comment]
Want to sumbit a PR?

**Comment by zukkun** [comment]
@ebidel I tried PR.
