### ISSUE TITLE
console error if I18nMsg.url changed (still goes to default locales url?)

### ISSUE THREAD

**Issue by carolirod** [ebidel/i18n-msg#21]
Just checking, shouldn't this NOT be happening? I mean the following error:

![screen shot 2015-09-11 at 21 28 38](https://cloud.githubusercontent.com/assets/770181/9824296/1bdc5722-58cc-11e5-9a63-ea4571e48477.png)

since I'm setting the I18nMsg.url to a custom one (just outside "../locales") and this new url is working because it's translating everything (meaning, it's correctly finding the locales folder etc.)

And still getting that error (I guess because it's trying to find the locales from the default location even though a new url was used?)

**Comment by ebidel** [comment]
Could be a race condition. We need tests!

Can you post a jsbin that repos the error or a complete block of code?

**Comment by carolirod** [comment]
Sure! For example:
```html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../i18n-msg/i18n-msg.html">

<dom-module id="test-karol">
  <link rel="import" type="css" href="test-karol.css">
  <template>
    <i18n-msg msgid="cards"></i18n-msg>
    <content></content>
  </template>
</dom-module>

<script>
  Polymer({
    is: 'test-karol'
  });
</script>
```

This would be the demo:
```
<link href="../test-karol.html" rel="import">
<test-karol></test-karol>
<script>
document.documentElement.lang = 'en';
document.addEventListener('HTMLImportsLoaded', function(){
  I18nMsg.url = '../locales';
  I18nMsg.lang = document.documentElement.lang;
});
</script>
```

And the folder structure:
![screen shot 2015-09-16 at 14 47 00](https://cloud.githubusercontent.com/assets/770181/9904913/d6578974-5c81-11e5-99f4-4e82999ccd8a.png)

And the error message (though with the i18n-msg fetching correctly the json from locales at the new url):
![screen shot 2015-09-16 at 14 48 03](https://cloud.githubusercontent.com/assets/770181/9905019/84c68dac-5c82-11e5-8a4a-38c1b557eb2a.png)

**Comment by ebidel** [comment]
I think this is working as intended. The .url property is setup for `locales` here: https://github.com/ebidel/i18n-msg/blob/master/i18n-msg.html#L75

When the element, loads, it using that directory, then at a later point (at `HTMLImportsLoaded`), you're setting it to `../locales`. That directory doesn't exist, so it's 404ing.

**Comment by carolirod** [comment]
it does make sense and actually we realized that with a colleague this week and so, just defining the I18nMsg.url before the instance of the tag solves it...

```html
<script>
document.documentElement.lang = 'en';
document.addEventListener('HTMLImportsLoaded', function() {
// fallback language is english
I18nMsg.lang = document.documentElement.lang || 'en';
I18nMsg.url = '../locales';
});
</script>
<test-karol></test-karol>
```

so my bad.. thanks and sorry for the trouble!
