### ISSUE TITLE
i18n-msg doesn't work in FF and Edge.

### ISSUE THREAD

**Issue by kysonic** [ebidel/i18n-msg#23]
I've tested this component in FireFox (41.0.2) and Edge (20.10240) and noticed that language doesn't switch. Also when i've put it into another component it wasn't displayed.

**Comment by soonick** [comment]
Hello @kysonic,

It is because those browsers don't support Object.observe. @ebidel is using https://github.com/polymer/observe-js, so you can fix it by calling:

```
Platform.performMicrotaskCheckpoint();
```

I created a pull request to fix the demo: https://github.com/ebidel/i18n-msg/pull/24

**Comment by kysonic** [comment]
@soonick Got it. I thought that webcomponents-lite.js contains some polyfill for this by default. Thanks for your help.
